// As respostas são as palavras que devem aparecer nas cartelas.
// A ordem cobre somente as 73 bolinhas que existem: 1–37, 40 e 46–80.
export const perguntas = {
  1: { question: 'Que arte ou espaço permite que atores representem uma história ao vivo diante de um público?', answer: 'Teatro', difficulty: 'facil' },
  2: { question: 'Qual ciência humana estuda a sociedade e as relações entre as pessoas?', answer: 'Sociologia', difficulty: 'facil' },
  3: { question: 'Que manifestação da criatividade humana expressa emoções, ideias e visões de mundo por sons, imagens, palavras ou movimentos?', answer: 'Arte', difficulty: 'medio' },
  4: { question: 'Que arte usa a palavra escrita ou falada para criar narrativas, poesias e outras expressões estéticas?', answer: 'Literatura', difficulty: 'medio' },
  5: { question: 'Que forma de conhecimento investiga fenômenos por meio de métodos sistemáticos, evidências e resultados verificáveis?', answer: 'Ciência', difficulty: 'dificil' },
  6: { question: 'Que idioma de origem neolatina é falado por milhões de pessoas em quatro continentes?', answer: 'Língua portuguesa', difficulty: 'medio' },
  7: { question: 'Como se chama a integração de conteúdos de duas ou mais disciplinas?', answer: 'Interdisciplinaridade', difficulty: 'facil' },
  8: { question: 'Qual língua germânica ocidental surgiu na Inglaterra e hoje é muito usada como segundo idioma no mundo?', answer: 'Inglês', difficulty: 'medio' },
  9: { question: 'Que plataforma elevada, fixa ou móvel, recebe apresentações?', answer: 'Palco', difficulty: 'facil' },
  10: { question: 'Qual área do conhecimento e componente curricular estuda e desenvolve as práticas corporais?', answer: 'Educação física', difficulty: 'facil' },
  11: { question: 'Como se chama uma subdivisão de um ato de uma peça teatral?', answer: 'Cena', difficulty: 'facil' },
  12: { question: 'Qual curso forma profissionais para estudar o processamento automático de informações por computadores e dispositivos digitais?', answer: 'Informática', difficulty: 'facil' },
  13: { question: 'Que documento serve como guia ou plano para a realização de uma obra?', answer: 'Roteiro', difficulty: 'medio' },
  14: { question: 'Qual curso prepara profissionais para atuar com desenho técnico, gráfico e computacional na construção civil?', answer: 'Edificações', difficulty: 'facil' },
  15: { question: 'Como se chama um ser fictício que participa de uma narrativa e realiza ações nela?', answer: 'Personagem', difficulty: 'facil' },
  16: { question: 'Qual curso estuda a geração, a transmissão, a distribuição e o uso da energia elétrica?', answer: 'Eletrotécnica', difficulty: 'medio' },
  17: { question: 'Como se chama o conjunto de artistas e atores que participa de uma obra?', answer: 'Elenco', difficulty: 'facil' },
  18: { question: 'Qual curso trata da instalação, do funcionamento, da manutenção e do reparo de máquinas e sistemas industriais?', answer: 'Mecânica Industrial', difficulty: 'facil' },
  19: { question: 'Quem interpreta e guia a encenação, coordenando o trabalho dos atores e da equipe técnica?', answer: 'Diretor', difficulty: 'facil' },
  20: { question: 'Qual ciência estuda a matéria, suas propriedades, sua composição e suas transformações?', answer: 'Química', difficulty: 'facil' },
  21: { question: 'Como se chama a etapa em que elenco, direção e equipe técnica experimentam e aperfeiçoam uma peça antes da estreia?', answer: 'Ensaio', difficulty: 'medio' },
  22: { question: 'Qual curso prepara profissionais para trabalhar com transmissão de dados, voz e imagens por redes, telefonia e internet?', answer: 'Telecomunicações', difficulty: 'facil' },
  23: { question: 'Como se chama o conjunto de roupas, calçados e acessórios usados por artistas ou personagens?', answer: 'Figurino', difficulty: 'facil' },
  24: { question: 'Quem acompanha os estudantes participantes da JAC e orienta o processo artístico e pedagógico da peça?', answer: 'Orientador Artístico-Pedagógico', difficulty: 'medio' },
  25: { question: 'Como se chama o conjunto de elementos que compõe e representa o ambiente de uma peça?', answer: 'Cenário', difficulty: 'facil' },
  26: { question: 'Qual é a sigla de Mostra Interdisciplinar Juventude, Arte e Ciência?', answer: 'JAC', difficulty: 'facil' },
  27: { question: 'Qual produto é aplicado no rosto ou no corpo para caracterizar personagens ou realçar a beleza?', answer: 'Maquiagem', difficulty: 'facil' },
  28: { question: 'Qual é a área lateral do palco, escondida do público, onde os atores aguardam para entrar em cena?', answer: 'Cochia', difficulty: 'facil' },
  29: { question: 'Como se chama o uso da luz, das cores e das sombras para criar efeitos visuais e emoções em uma apresentação?', answer: 'Iluminação', difficulty: 'medio' },
  30: { question: 'Como se chama o conjunto de elementos naturais e artificiais que cerca os seres vivos e influencia suas vidas?', answer: 'Meio ambiente', difficulty: 'facil' },
  31: { question: 'Qual é a arte e a técnica de criar, selecionar e manipular sons?', answer: 'Sonoplastia', difficulty: 'facil' },
  32: { question: 'Como se chama o uso equilibrado, consciente e responsável dos recursos naturais?', answer: 'Sustentabilidade', difficulty: 'medio' },
  33: { question: 'Como se chama tudo o que acontece fora da vista do público durante a preparação de um espetáculo?', answer: 'Bastidores', difficulty: 'medio' },
  34: { question: 'Como se chama o conjunto de ações de planejamento, organização, orçamento, logística e gestão de um evento?', answer: 'Produção', difficulty: 'medio' },
  35: { question: 'Como se chama o espaço do teatro onde ficam os espectadores?', answer: 'Plateia', difficulty: 'facil' },
  36: { question: 'Qual capacidade permite adquirir, guardar e recuperar informações e experiências ao longo do tempo?', answer: 'Memória', difficulty: 'medio' },
  37: { question: 'Como se chama uma apresentação pública criada para mostrar uma obra e entreter o público?', answer: 'Espetáculo', difficulty: 'facil' },
  40: { question: 'Como se chama o conjunto de conhecimentos, crenças, valores, costumes, artes e práticas compartilhados por um grupo?', answer: 'Cultura', difficulty: 'medio' },
  46: { question: 'Qual arte expressa sentimentos, ideias e histórias por meio de movimentos corporais ritmados?', answer: 'Dança', difficulty: 'facil' },
  47: { question: 'Qual arte e técnica organiza textos escritos para serem representados no palco?', answer: 'Dramaturgia', difficulty: 'medio' },
  48: { question: 'Qual língua brasileira de modalidade visual-espacial é usada pela comunidade surda no Brasil?', answer: 'Libras', difficulty: 'facil' },
  49: { question: 'Como se chama a arte de interpretar personagens no teatro e em outras artes cênicas?', answer: 'Atuação', difficulty: 'medio' },
  50: { question: 'Qual capacidade ajuda a criar, inventar e encontrar soluções originais para problemas?', answer: 'Criatividade', difficulty: 'medio' },
  51: { question: 'Como se chama criar falas ou ações no momento, sem preparação ou roteiro definido?', answer: 'Improvisação', difficulty: 'medio' },
  52: { question: 'Qual capacidade permite formar imagens e situações na mente mesmo sem tê-las diante dos olhos?', answer: 'Imaginação', difficulty: 'medio' },
  53: { question: 'Como se chama o uso de movimentos, posturas e gestos para transmitir ideias ou emoções?', answer: 'Expressão corporal', difficulty: 'medio' },
  54: { question: 'Que atividade busca, reúne e analisa informações para responder a uma pergunta ou compreender um assunto?', answer: 'Pesquisa', difficulty: 'medio' },
  55: { question: 'Como se chama o som produzido pela passagem de ar pelas pregas vocais e usado na fala e no canto?', answer: 'Voz', difficulty: 'facil' },
  56: { question: 'Qual é a sigla do Instituto Federal de Educação, Ciência e Tecnologia do Ceará?', answer: 'IFCE', difficulty: 'facil' },
  57: { question: 'Como se chama um movimento de uma parte do corpo que comunica uma ideia ou sentimento?', answer: 'Gesto', difficulty: 'facil' },
  58: { question: 'Que procedimento é feito para observar um fenômeno ou verificar uma hipótese?', answer: 'Experimento', difficulty: 'medio' },
  59: { question: 'Como se chama a mudança de posição de um corpo no espaço ao longo do tempo?', answer: 'Movimento', difficulty: 'medio' },
  60: { question: 'Como se chama o conjunto de informações, habilidades e compreensões adquirido por estudo ou experiência?', answer: 'Conhecimento', difficulty: 'dificil' },
  61: { question: 'Como se chama uma fala longa feita por uma única pessoa ou personagem?', answer: 'Monólogo', difficulty: 'medio' },
  62: { question: 'Qual é o processo de adquirir conhecimentos, habilidades ou atitudes?', answer: 'Aprendizagem', difficulty: 'facil' },
  63: { question: 'Como se chama uma conversa entre duas ou mais pessoas, com troca de falas?', answer: 'Diálogo', difficulty: 'facil' },
  64: { question: 'Como se chama algo recebido como reconhecimento por uma conquista ou participação, como uma medalha ou um troféu?', answer: 'Prêmio', difficulty: 'facil' },
  65: { question: 'Qual gênero teatral costuma provocar riso por meio de situações engraçadas?', answer: 'Comédia', difficulty: 'facil' },
  66: { question: 'Como se chama definir objetivos, etapas, recursos e prazos antes de realizar uma atividade?', answer: 'Planejamento', difficulty: 'medio' },
  67: { question: 'Qual gênero teatral apresenta conflitos intensos e acontecimentos que podem levar a um desfecho doloroso?', answer: 'Tragédia', difficulty: 'medio' },
  68: { question: 'Como se chama o ato de dispor pessoas, tarefas e materiais de forma ordenada?', answer: 'Organização', difficulty: 'facil' },
  69: { question: 'Como se chama o conjunto de acontecimentos relacionados que formam uma história?', answer: 'Narrativa', difficulty: 'medio' },
  70: { question: 'Como se chama a troca ou transmissão de informações, ideias e sentimentos entre pessoas?', answer: 'Comunicação', difficulty: 'medio' },
  71: { question: 'Qual disciplina estuda números, formas, medidas, estruturas e relações?', answer: 'Matemática', difficulty: 'medio' },
  72: { question: 'Como se chama a capacidade de agir e tomar decisões por conta própria com responsabilidade?', answer: 'Autonomia', difficulty: 'medio' },
  73: { question: 'Qual ciência estuda a matéria, a energia, o movimento e suas interações?', answer: 'Física', difficulty: 'dificil' },
  74: { question: 'Como se chama a participação ativa e central de alguém em uma ação ou história?', answer: 'Protagonismo', difficulty: 'medio' },
  75: { question: 'Qual capacidade permite analisar argumentos, questionar pressupostos e formar uma opinião fundamentada?', answer: 'Pensamento crítico', difficulty: 'dificil' },
  76: { question: 'Qual ciência estuda os seres vivos e suas relações entre si e com o ambiente?', answer: 'Biologia', difficulty: 'dificil' },
  77: { question: 'Como se chama uma reação subjetiva diante de uma situação, como alegria, medo ou tristeza?', answer: 'Emoção', difficulty: 'facil' },
  78: { question: 'Qual área estuda as sociedades humanas ao longo do tempo com base em acontecimentos e fontes?', answer: 'História', difficulty: 'medio' },
  79: { question: 'Como se chama o processo pelo qual algo ou alguém se modifica?', answer: 'Transformação', difficulty: 'medio' },
  80: { question: 'Qual ciência estuda os lugares e as relações entre a sociedade e o espaço?', answer: 'Geografia', difficulty: 'medio' },
};

export const numerosSemBolinha = [38, 39, 41, 42, 43, 44, 45];
export const numeros = Object.keys(perguntas).map(Number).sort((a, b) => a - b);
